baseURL = "http://example.com/"
languageCode = "en-us"
title = "Preparing to Teach"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Mine Cetinkaya-Rundel"
    description = "Workshop to prepare graduate students for a role as undergraduate faculty responsible for teaching statistics and data science"
    accent = "#007CB7"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
    
[[menu.main]]
    url = "/apply/"
    name = "Apply"
    weight = 3

[[menu.main]]
    url = "/agenda/"
    name = "Agenda"
    weight = 4

[[menu.main]]
    url = "/presenters/"
    name = "Presenters"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:cetinkaya.mine@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mine-cetinkaya-rundel/preparing-to-teach-web"
    name = "github"
    weight = 2
